import Head from "next/head";
import { Slider } from "../components/Slider";
import { client } from "../libs/client";

export default function Home({ banners }) {
  return (
    <div>
      <Head>
        <title>名古屋万博</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>名古屋万博</h1>
      </header>
      <Slider banners={banners}></Slider>
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "banners" });

  return {
    props: {
      banners: data.contents,
    },
  };
};
