import Head from "next/head";
import { Slider } from "../components/Slider";
import { client } from "../libs/client";
import "bootstrap/dist/css/bootstrap.min.css";
import TopView from "../components/TopView";
import { Shops } from "../components/Shops";

export default function Home({ banners }) {
  return (
    <div>
      <Head>
        <title>名古屋万博</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>名古屋万博</h1>
      </header>
      <TopView></TopView>
      <div className="container pt-5">
        <Shops title={"飲食店"}></Shops>
      </div>
      <footer></footer>
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({ endpoint: "banners" });

  return {
    props: {
      banners: data.contents,
    },
  };
};
