import Head from "next/head";
import { Slider } from "../components/Slider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>名古屋万博</h1>
      </header>
      <Slider></Slider>
    </div>
  );
}
